/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.okruss.GUI;

import com.mysql.jdbc.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;
import org.okruss.CNC.classes.conex;
import org.okruss.CNC.classes.file_browser;
import org.okruss.CNC.classes.reportes;

/**
 *
 * @author Okruss
 */
public class corregirDatos extends javax.swing.JFrame {
    
    String llave="";
    String letra="", clave="", folio="";
        conex cone = new conex();
        reportes report= new reportes();
        file_browser fl = new file_browser();
        Connection con;
        Statement stmt = null;
    /**
     * Creates new form corregirDatos
     */
    public corregirDatos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACTUALIZAR DATOS");

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("ACTUALIZAR REGISTROS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        final JProgressBar barraProgreso = new JProgressBar(0, 1000);
                final JDialog dialogoProgreso = new JDialog(this, "Procesando...");
                dialogoProgreso.getContentPane().add(barraProgreso);
                dialogoProgreso.pack();
                dialogoProgreso.setLocationRelativeTo(null);
                final javax.swing.SwingWorker worker;
                worker = new javax.swing.SwingWorker() {
            
                @Override
                protected Void doInBackground() throws Exception {
                dialogoProgreso.setVisible(true);
                barraProgreso.setVisible(true);
                barraProgreso.setIndeterminate(true);
                try
                    {
                        for(int x=0; x<tabla.getRowCount();x++)
                            {
                            System.out.println("LLAVE PARA LA FILA:"+tabla.getValueAt(x,0)+"///////////////");
                            
                                for (int c=1; c<tabla.getColumnCount();c++)
                                    {
                                        stmt=(Statement) cone.conexion();
                                        stmt.getConnection();
                                        stmt.executeUpdate("use credito");
                                        System.out.println("update padron set "+tabla.getColumnName(c)+"='"+tabla.getValueAt(x, c)+"' where llave='"+tabla.getValueAt(x,0)+"'");
                                        stmt.executeUpdate("update padron set "+tabla.getColumnName(c)+"='"+tabla.getValueAt(x, c)+"' where llave='"+tabla.getValueAt(x,0)+"'");
                                        //System.out.println(tabla.getColumnName(c)+"::"+tabla.getValueAt(x,c));
                                        
                                    }
                            }
                        JOptionPane.showMessageDialog(null,"SE ACTUALIZARON LOS REGISTROS");
                    
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
                    e.printStackTrace();
                }
                                
                return null;
            }

            @Override
            protected void done() {
                barraProgreso.setIndeterminate(false);;
                barraProgreso.setVisible(false);
                dialogoProgreso.setVisible(false);
            }
        };
        worker.execute();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        final JProgressBar barraProgreso = new JProgressBar(0, 1000);
        final JDialog dialogoProgreso = new JDialog(this, "Procesando...");
        dialogoProgreso.getContentPane().add(barraProgreso);
        dialogoProgreso.pack();
        dialogoProgreso.setLocationRelativeTo(null);

        final javax.swing.SwingWorker worker;
        worker = new javax.swing.SwingWorker() {
            
            @Override
            protected Void doInBackground() throws Exception {
                dialogoProgreso.setVisible(true);
                barraProgreso.setVisible(true);
                barraProgreso.setIndeterminate(true);
                try
                {
                    stmt=cone.conexion();
                    stmt.getConnection();
                    stmt.executeUpdate("use credito");
                    ResultSet rs=stmt.executeQuery("Select * from padron where "
                            + "llave='"+llave+"'");

                    ResultSetMetaData mD = rs.getMetaData();
                    int ncol=mD.getColumnCount();
                    Object label [] = new Object [ncol];
                    for (int i=0;i<ncol;i++)
                    {
                        label[i]=mD.getColumnLabel(i+1);
                    }

                    DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
                    modelo.setRowCount(0);
                    modelo.setColumnIdentifiers(label);
                    while(rs.next())
                    {
                        Object [] fila = new Object [ncol];
                        for (int i=0;i<ncol;i++)
                        {
                            fila[i]=rs.getObject(i+1);
                        }
                        modelo.addRow(fila);
                    }
                }
                catch (Exception e)
                {
                    JOptionPane.showMessageDialog(null,"Error:"+e.getMessage());
                    e.printStackTrace();
                }
                                
                return null;
            }

            @Override
            protected void done() {
                barraProgreso.setIndeterminate(false);;
                barraProgreso.setVisible(false);
                dialogoProgreso.setVisible(false);
            }
        };
        worker.execute();
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(corregirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(corregirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(corregirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(corregirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new corregirDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
